### PR TITLE
Fix title on CMS login page (#191)

### LINKED ISSUE #191: The title on the CMS login page is not displaying.. Fix this
image

### PR DESCRIPTION
**Pull request by handshek**
Fixes #191 

- Add a title to the CMS login page.
- The following is a screenshot of the applied change.

cms-title

### CODE REVIEW

**Comment by Bowens20832** [comment]
Awesome! 

Looks perfect 😄 

Thank you for the help and contribution.

**Comment by handshek** [comment]
> Awesome!
> 
> Looks perfect 😄
> 
> Thank you for the help and contribution.

Hey, no need to mention it.

I'm participating in this year's hacktoberfest and it would truly help if you could kindly add the label `hacktoberfest-accepted` to this PR. Of course, no worries at all if it's not possible.

Thanks for the opportunity!

**Comment by Bowens20832** [comment]
> > Awesome!
> > Looks perfect 😄
> > Thank you for the help and contribution.
> 
> Hey, no need to mention it.
> 
> I'm participating in this year's hacktoberfest and it would truly help if you could kindly add the label `hacktoberfest-accepted` to this PR. Of course, no worries at all if it's not possible.
> 
> Thanks for the opportunity!

Merged!

Thanks for the help 💯

**Comment by handshek** [comment]
Thanks a lot!

**Pull request merged**
