### PR TITLE
Legal Namespace and Trademark Page

### LINKED ISSUE #42: As a content creator, I would like my web application to include a basic trademark policy page.

### PR DESCRIPTION
**Pull request by rabisnaqvi**
- Added the legal namespace, with a trademark-policy.mdx file.
- Configured next to use BasicLayout on the legal namespace.
- Created boilerplate code using ENV variables.
- Created a Utility to use ENV variables inside .mdx files as components.
- I wasn't able to get the markdown formatting to work properly, so, for now, I have used HTML for formatting.

### CODE REVIEW

**Comment by rabisnaqvi** [comment]
@Bowens20832 please review :)

**Comment by Bowens20832** [comment]
> @Bowens20832 please review :)

This is awesome!

**Comment by rabisnaqvi** [comment]
Happy to contribute 🤗
Cheers! 🍻

**Comment by Bowens20832** [comment]
> Happy to contribute 🤗 Cheers! 🍻

How'd you feel about the project so far? Do you have any feedback or ideas for improvement?

**Comment by rabisnaqvi** [comment]
It seems that Astro is doing a lot of what Elegant is striving to do. The concept of using markdown as static content is really good, and I think that concept has a lot of potential, but with Astro already doing that, it won't be the unique selling point for Elegant. I think Elegant needs to have something which should be unique to its existence, that would be needed to drive attention to it!
In terms of technology, I love Next, so no complaints in that department!

**Comment by Bowens20832** [comment]
> It seems that Astro is doing a lot of what Elegant is striving to do. The concept of using markdown as static content is really good, and I think that concept has a lot of potential, but with Astro already doing that, it won't be the unique selling point for Elegant. I think Elegant needs to have something which should be unique to its existence, that would be needed to drive attention to it! In terms of technology, I love Next, so no complaints in that department!

Hey thank you for the feedback! I hadn't even spent much time looking at Astro before, but yeah it does seem to have some similarites between the two projects. I love how Astro intergrates with everything already, but I'm not a big fan of them having their own file names and stuff. I just want to create beautiful apps with React, without having to learn another vendors styling and quirks.

I love Next.js, Tailwind CSS, and Markdown, so I've been wrapping up the best technoligies into a single simple to use project for creating new apps without worrying about all the boilerplate code. 

I believe the market is saying that WordPress is outdated, and they would like something more simple that is built on top of the latest technology. 

@rabisnaqvi What do you think?

MicrosoftTeams-image (5)
MicrosoftTeams-image (6)

**Comment by rabisnaqvi** [comment]
> > It seems that Astro is doing a lot of what Elegant is striving to do. The concept of using markdown as static content is really good, and I think that concept has a lot of potential, but with Astro already doing that, it won't be the unique selling point for Elegant. I think Elegant needs to have something which should be unique to its existence, that would be needed to drive attention to it! In terms of technology, I love Next, so no complaints in that department!
> 
> Hey thank you for the feedback! I hadn't even spent much time looking at Astro before, but yeah it does seem to have some similarites between the two projects. I love how Astro intergrates with everything already, but I'm not a big fan of them having their own file names and stuff. I just want to create beautiful apps with React, without having to learn another vendors styling and quirks.
> 
> I love Next.js, Tailwind CSS, and Markdown, so I've been wrapping up the best technoligies into a single simple to use project for creating new apps without worrying about all the boilerplate code. 
> 
> I believe the market is saying that WordPress is outdated, and they would like something more simple that is built on top of the latest technology. 
> 
> @rabisnaqvi What do you think?
> 
> MicrosoftTeams-image (5)
> MicrosoftTeams-image (6)
> 

I love that you are trying to make it more like a CMS. I have used wordpress myself for a good lot of time and yes, with the rise of serverless technologies, it's time to move ahead from wordpress. But the thing that ensured WordPress's success was its easy customizability, ability to customize inner workings via extensions and themes, a good lot of pre-built themes and extensions etc, i think if we move Elegant in that direction, it would make much more sense! Providing easy and straightforward extendability and customizability would be the USP for Elegant. Also, a good way to ensure good and easy UX, is an admin panel/portal. What if instead a user creating the file manually in the codebase, Elegant handled that for the user via a built-in markdown page builder.
I can see a lot of potential and i have so many suggestions! If Elegant becomes a generic enough tool, there's no doubt it would solve a lot of problems and hence grab attention.
Looking forward to contributing to this project more, let me know what you want me to pick up next!

**Comment by Bowens20832** [comment]
> > > It seems that Astro is doing a lot of what Elegant is striving to do. The concept of using markdown as static content is really good, and I think that concept has a lot of potential, but with Astro already doing that, it won't be the unique selling point for Elegant. I think Elegant needs to have something which should be unique to its existence, that would be needed to drive attention to it! In terms of technology, I love Next, so no complaints in that department!
> > 
> > 
> > Hey thank you for the feedback! I hadn't even spent much time looking at Astro before, but yeah it does seem to have some similarites between the two projects. I love how Astro intergrates with everything already, but I'm not a big fan of them having their own file names and stuff. I just want to create beautiful apps with React, without having to learn another vendors styling and quirks.
> > I love Next.js, Tailwind CSS, and Markdown, so I've been wrapping up the best technoligies into a single simple to use project for creating new apps without worrying about all the boilerplate code.
> > I believe the market is saying that WordPress is outdated, and they would like something more simple that is built on top of the latest technology.
> > @rabisnaqvi What do you think?
> > MicrosoftTeams-image (5)
> > MicrosoftTeams-image (6)
> 
> I love that you are trying to make it more like a CMS. I have used wordpress myself for a good lot of time and yes, with the rise of serverless technologies, it's time to move ahead from wordpress. But the thing that ensured WordPress's success was its easy customizability, ability to customize inner workings via extensions and themes, a good lot of pre-built themes and extensions etc, i think if we move Elegant in that direction, it would make much more sense! Providing easy and straightforward extendability and customizability would be the USP for Elegant. Also, a good way to ensure good and easy UX, is an admin panel/portal. What if instead a user creating the file manually in the codebase, Elegant handled that for the user via a built-in markdown page builder. I can see a lot of potential and i have so many suggestions! If Elegant becomes a generic enough tool, there's no doubt it would solve a lot of problems and hence grab attention. Looking forward to contributing to this project more, let me know what you want me to pick up next!

@rabisnaqvi I agree 100%! I opened a discussion to collect some ideas on an admin panel #49 

Do you have any suggestions on any admin panels?

**Comment by Bowens20832** [comment]
The trademark policy is now live: [Elegant Trademark Policy](https://www.elegantframework.com/legal/trademark-policy)

Thank you 💯 @rabisnaqvi !

**Pull request merged**
